[package]
name = "to_params"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.91"
util = {version = "*", path = "../../util"}

[dev-dependencies]
serde_json.workspace = true
