[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
minijinja.workspace = true
minijinja-embed = "2.5.0"
model = { version = "0.1.0", path = "../model" }
util = { version = "0.1.0", path = "../util" }

[build-dependencies]
minijinja-embed = "2.5.0"
