networks:
  api-dev:
    driver: bridge
services:
  database:
    image: ghcr.io/fboulnois/pg_uuidv7:1.6.0
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      PGPASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - ${PG_PORT}:5432
  auth: 
    image: casbin/casdoor-all-in-one 
    ports:
      - 3001:8000
  redis:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379

volumes:
  database-data:
