networks:
  api-dev:
    driver: bridge
services:
  test-database:
    image: ghcr.io/fboulnois/pg_uuidv7:1.6.0
    environment:
      POSTGRES_USER: rwusertest
      POSTGRES_PASSWORD: test 
      PGPASSWORD: test
      POSTGRES_DB: api_template
  test-redis:
    image: redis:latest
    ports:
      - 6380:6379
    ports:
      - 5436:5432
