[package]
name = "derive_update_model"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.91"

[dev-dependencies]
serde_json.workspace = true
