CREATE USER rouser WITH PASSWORD 'test';
GRANT CONNECT ON DATABASE api_template  TO rouser;
GRANT USAGE ON SCHEMA public TO rouser;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO rouser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA PUBLIC TO rouser;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO rouser;

CREATE EXTENSION pg_uuidv7;
